eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    leaseExpirationDurationInSeconds: 2
    leaseRenewalIntervalInSeconds: 1
jwt:
  get:
    token:
      uri: /authenticate
  http:
    request:
      header: Authorization
  refresh:
    token:
      uri: /refresh
  signing:
    key:
      secret: mySecret
  token:
    expiration:
      in:
        seconds: 3600
server:
  port: 8000
spring:
  application:
    name: burger-auth
  datasource:
    password: admin
    url: jdbc:mysql://localhost:3306/burger?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
