server:
  port: 9010
spring:
  application:
    name: burger-server-task
  datasource:
    url: jdbc:mysql://localhost:3306/taskdb?createDatabaseIfNotExist=true
    username: root
    password: admin
